// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pill-scheme/Current.tsx": () => import("../components/mockups/pill-scheme/Current.tsx"),
  "./components/mockups/pill-scheme/IceBlue.tsx": () => import("../components/mockups/pill-scheme/IceBlue.tsx"),
  "./components/mockups/pill-scheme/WarmAmber.tsx": () => import("../components/mockups/pill-scheme/WarmAmber.tsx"),
  "./components/mockups/pill-scheme/WhiteGhost.tsx": () => import("../components/mockups/pill-scheme/WhiteGhost.tsx")
};
